export enum TaskType {
  MARK_IMPORTANT = 'MARK_IMPORTANT',
  MOVE_FROM_SPAM = 'MOVE_FROM_SPAM',
  REPLY_EMAIL = 'REPLY_EMAIL',
  FORWARD_EMAIL = 'FORWARD_EMAIL',
  DELETE_EMAIL = 'DELETE_EMAIL',
  ARCHIVE_EMAIL = 'ARCHIVE_EMAIL',
  LABEL_EMAIL = 'LABEL_EMAIL',
  STAR_EMAIL = 'STAR_EMAIL',
  SEND_EMAIL = 'SEND_EMAIL',
  MOVE_TO_INBOX = 'MOVE_TO_INBOX',
  MARK_AS_READ = 'MARK_AS_READ',
  MARK_AS_UNREAD = 'MARK_AS_UNREAD',
  MOVE_TO_TRASH = 'MOVE_TO_TRASH',
  RESTORE_FROM_TRASH = 'RESTORE_FROM_TRASH'
}

export enum TaskStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
} 