version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/email_warmup
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017/email_warmup
    depends_on:
      - db
      - redis
      - mongodb
    volumes:
      - .:/app
    networks:
      - email_warmup_network

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/email_warmup
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017/email_warmup
    depends_on:
      - db
      - redis
      - mongodb
    volumes:
      - .:/app
    networks:
      - email_warmup_network

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    command: celery -A app.tasks.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/email_warmup
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017/email_warmup
    depends_on:
      - db
      - redis
      - mongodb
    volumes:
      - .:/app
    networks:
      - email_warmup_network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=email_warmup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - email_warmup_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - email_warmup_network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - email_warmup_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    networks:
      - email_warmup_network

volumes:
  postgres_data:
  redis_data:
  mongodb_data:

networks:
  email_warmup_network:
    driver: bridge 