import { app, BrowserWindow, ipcMain, net } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Get API base URL based on environment
const getApiBaseUrl = (): string => {
  if (process.env.NODE_ENV === 'development') {
    return 'http://localhost:3001/api';
  } else {
    // In production, API should be on the same host
    return `http://${process.env.API_HOST || 'localhost:3001'}/api`;
  }
};

// Function to get full API URL
const getFullApiUrl = (endpoint: string): string => {
  return `${getApiBaseUrl()}${endpoint}`;
};

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    autoHideMenuBar: true,
    title: 'Email Warmer',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
  // Open DevTools in development mode
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
};

// Register IPC handlers for API requests
const registerIpcHandlers = (): void => {
  console.log('Registering IPC handlers for API calls...');
  
  // Get all pipelines
  ipcMain.handle('api:getPipelines', async () => {
    return new Promise((resolve, reject) => {
      console.log('Fetching pipelines from:', getFullApiUrl('/pipelines'));
      const request = net.request(getFullApiUrl('/pipelines'));
      
      let responseData = '';
      
      request.on('response', (response) => {
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Received pipeline data:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse pipeline data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when fetching pipelines:', error);
        reject(error);
      });
      
      request.end();
    });
  });
  
  // Get pipeline by ID
  ipcMain.handle('api:getPipelineById', async (event, id) => {
    return new Promise((resolve, reject) => {
      console.log('Fetching pipeline by ID:', id);
      const request = net.request(getFullApiUrl(`/pipelines/${id}`));
      
      let responseData = '';
      
      request.on('response', (response) => {
        if (response.statusCode === 404) {
          console.log('Pipeline not found:', id);
          resolve(null);
          return;
        }
        
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Received pipeline:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse pipeline data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when fetching pipeline:', error);
        reject(error);
      });
      
      request.end();
    });
  });
  
  // Save pipeline
  ipcMain.handle('api:savePipeline', async (event, pipeline) => {
    return new Promise((resolve, reject) => {
      const method = pipeline.id ? 'PUT' : 'POST';
      const url = pipeline.id 
        ? getFullApiUrl(`/pipelines/${pipeline.id}`)
        : getFullApiUrl('/pipelines');
      
      console.log(`${method} request to save pipeline:`, url, pipeline);
      
      const request = net.request({
        method,
        url
      });
      
      request.setHeader('Content-Type', 'application/json');
      
      let responseData = '';
      
      request.on('response', (response) => {
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Pipeline saved:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse response data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when saving pipeline:', error);
        reject(error);
      });
      
      request.write(JSON.stringify(pipeline));
      request.end();
    });
  });
  
  // Delete pipeline
  ipcMain.handle('api:deletePipeline', async (event, id) => {
    return new Promise((resolve, reject) => {
      console.log('Deleting pipeline:', id);
      
      const request = net.request({
        method: 'DELETE',
        url: getFullApiUrl(`/pipelines/${id}`)
      });
      
      request.on('response', (response) => {
        if (response.statusCode === 404) {
          console.log('Pipeline not found for deletion:', id);
          resolve(false);
          return;
        }
        
        if (response.statusCode === 204 || response.statusCode === 200) {
          console.log('Pipeline deleted successfully:', id);
          resolve(true);
          return;
        }
        
        reject(new Error(`Unexpected status code: ${response.statusCode}`));
      });
      
      request.on('error', (error) => {
        console.error('Network error when deleting pipeline:', error);
        reject(error);
      });
      
      request.end();
    });
  });
  
  // Get environment info
  ipcMain.handle('getEnvironment', async () => {
    return {
      nodeEnv: process.env.NODE_ENV || 'production',
      isPackaged: app.isPackaged,
      appVersion: app.getVersion(),
      platform: process.platform,
      apiBaseUrl: getApiBaseUrl()
    };
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  // Register IPC handlers first
  registerIpcHandlers();
  
  // Then create the window
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
