import { app, BrowserWindow, ipcMain, net } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Get API base URL based on environment
const getApiBaseUrl = (): string => {
  if (process.env.NODE_ENV === 'development') {
    return 'http://localhost:3001/api';
  } else {
    // In production, API should be on the same host
    return `http://${process.env.API_HOST || 'localhost:3001'}/api`;
  }
};

// Function to get full API URL
const getFullApiUrl = (endpoint: string): string => {
  return `${getApiBaseUrl()}${endpoint}`;
};

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    autoHideMenuBar: true,
    title: 'Email Warmer',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
  // Open DevTools in development mode
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
};

// Register IPC handlers for API requests
const registerIpcHandlers = (): void => {
  console.log('Registering IPC handlers for API calls...');
  
  // Get all pipelines
  ipcMain.handle('api:getPipelines', async () => {
    return new Promise((resolve, reject) => {
      console.log('Fetching pipelines from:', getFullApiUrl('/pipelines'));
      
      try {
        const request = net.request(getFullApiUrl('/pipelines'));
        
        let responseData = '';
        
        request.on('response', (response) => {
          console.log('Get pipelines response status:', response.statusCode);
          
          response.on('data', (chunk) => {
            responseData += chunk.toString();
            console.log('Pipelines chunk received, length:', chunk.toString().length);
          });
          
          response.on('end', () => {
            try {
              console.log('Raw pipelines response:', responseData);
              if (!responseData || responseData.trim() === '') {
                console.log('Empty response received for pipelines');
                // Return mock data
                resolve([
                  {
                    id: 'mock-1',
                    name: 'Demo Pipeline',
                    nodes: [
                      { id: '1', action: 'Transfer from Spam to Inbox' },
                      { id: '2', action: 'Click Link in Email' }
                    ],
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString()
                  }
                ]);
                return;
              }
              
              const data = JSON.parse(responseData);
              console.log('Received pipeline data:', data);
              resolve(data);
            } catch (error) {
              console.error('Failed to parse pipeline data:', error);
              console.error('Response data that failed to parse:', responseData);
              // Return mock data
              resolve([
                {
                  id: 'mock-1',
                  name: 'Demo Pipeline',
                  nodes: [
                    { id: '1', action: 'Transfer from Spam to Inbox' },
                    { id: '2', action: 'Click Link in Email' }
                  ],
                  createdAt: new Date().toISOString(),
                  updatedAt: new Date().toISOString()
                }
              ]);
            }
          });
        });
        
        request.on('error', (error) => {
          console.error('Network error when fetching pipelines:', error);
          // Return mock data
          resolve([
            {
              id: 'mock-1',
              name: 'Demo Pipeline',
              nodes: [
                { id: '1', action: 'Transfer from Spam to Inbox' },
                { id: '2', action: 'Click Link in Email' }
              ],
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString()
            }
          ]);
        });
        
        request.end();
      } catch (error) {
        console.error('Unexpected error in getPipelines:', error);
        // Return mock data
        resolve([
          {
            id: 'mock-1',
            name: 'Demo Pipeline',
            nodes: [
              { id: '1', action: 'Transfer from Spam to Inbox' },
              { id: '2', action: 'Click Link in Email' }
            ],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
          }
        ]);
      }
    });
  });
  
  // Get pipeline by ID
  ipcMain.handle('api:getPipelineById', async (event, id) => {
    return new Promise((resolve, reject) => {
      console.log('Fetching pipeline by ID:', id);
      const request = net.request(getFullApiUrl(`/pipelines/${id}`));
      
      let responseData = '';
      
      request.on('response', (response) => {
        if (response.statusCode === 404) {
          console.log('Pipeline not found:', id);
          resolve(null);
          return;
        }
        
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Received pipeline:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse pipeline data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when fetching pipeline:', error);
        reject(error);
      });
      
      request.end();
    });
  });
  
  // Save pipeline
  ipcMain.handle('api:savePipeline', async (event, pipeline) => {
    return new Promise((resolve, reject) => {
      const method = pipeline.id ? 'PUT' : 'POST';
      const url = pipeline.id 
        ? getFullApiUrl(`/pipelines/${pipeline.id}`)
        : getFullApiUrl('/pipelines');
      
      console.log(`${method} request to save pipeline:`, url, pipeline);
      
      const request = net.request({
        method,
        url
      });
      
      request.setHeader('Content-Type', 'application/json');
      
      let responseData = '';
      
      request.on('response', (response) => {
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Pipeline saved:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse response data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when saving pipeline:', error);
        reject(error);
      });
      
      request.write(JSON.stringify(pipeline));
      request.end();
    });
  });
  
  // Delete pipeline
  ipcMain.handle('api:deletePipeline', async (event, id) => {
    return new Promise((resolve, reject) => {
      console.log('Deleting pipeline:', id);
      
      const request = net.request({
        method: 'DELETE',
        url: getFullApiUrl(`/pipelines/${id}`)
      });
      
      request.on('response', (response) => {
        if (response.statusCode === 404) {
          console.log('Pipeline not found for deletion:', id);
          resolve(false);
          return;
        }
        
        if (response.statusCode === 204 || response.statusCode === 200) {
          console.log('Pipeline deleted successfully:', id);
          resolve(true);
          return;
        }
        
        reject(new Error(`Unexpected status code: ${response.statusCode}`));
      });
      
      request.on('error', (error) => {
        console.error('Network error when deleting pipeline:', error);
        reject(error);
      });
      
      request.end();
    });
  });
  
  // Get environment info
  ipcMain.handle('getEnvironment', async () => {
    return {
      nodeEnv: process.env.NODE_ENV || 'production',
      isPackaged: app.isPackaged,
      appVersion: app.getVersion(),
      platform: process.platform,
      apiBaseUrl: getApiBaseUrl()
    };
  });
  
  // Get available actions
  ipcMain.handle('api:getAvailableActions', async () => {
    return new Promise((resolve, reject) => {
      console.log('Fetching available actions from:', getFullApiUrl('/actions'));
      const request = net.request(getFullApiUrl('/actions'));
      
      let responseData = '';
      
      request.on('response', (response) => {
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Received available actions:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse actions data:', error);
            // Fallback to predefined actions if API fails
            resolve([
              'Transfer from Spam to Inbox',
              'Click Link in Email',
              'Mark as Important',
              'Reply to Email',
              'Forward Email',
              'Delete Email'
            ]);
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when fetching actions:', error);
        // Fallback to predefined actions if API fails
        resolve([
          'Transfer from Spam to Inbox',
          'Click Link in Email',
          'Mark as Important',
          'Reply to Email',
          'Forward Email',
          'Delete Email'
        ]);
      });
      
      request.end();
    });
  });

  // Get all email accounts
  ipcMain.handle('api:getEmailAccounts', async () => {
    return new Promise((resolve, reject) => {
      console.log('Fetching email accounts from:', getFullApiUrl('/email-accounts'));
      const request = net.request(getFullApiUrl('/email-accounts'));
      
      let responseData = '';
      
      request.on('response', (response) => {
        console.log('Email accounts response status:', response.statusCode);
        
        response.on('data', (chunk) => {
          responseData += chunk.toString();
          console.log('Email accounts chunk received, length:', chunk.toString().length);
        });
        
        response.on('end', () => {
          try {
            console.log('Raw email accounts response:', responseData);
            if (!responseData || responseData.trim() === '') {
              console.log('Empty response received for email accounts');
              resolve([]);
              return;
            }
            
            const data = JSON.parse(responseData);
            console.log('Received email accounts data:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse email accounts data:', error);
            console.error('Response data that failed to parse:', responseData);
            // Resolve with empty array instead of rejecting to avoid breaking the UI
            resolve([]);
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when fetching email accounts:', error);
        // Resolve with empty array instead of rejecting to avoid breaking the UI
        resolve([]);
      });
      
      request.end();
    });
  });

  // Get email account by ID
  ipcMain.handle('api:getEmailAccountById', async (event, id) => {
    return new Promise((resolve, reject) => {
      console.log('Fetching email account by ID:', id);
      const request = net.request(getFullApiUrl(`/email-accounts/${id}`));
      
      let responseData = '';
      
      request.on('response', (response) => {
        if (response.statusCode === 404) {
          console.log('Email account not found:', id);
          resolve(null);
          return;
        }
        
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Received email account:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse email account data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when fetching email account:', error);
        reject(error);
      });
      
      request.end();
    });
  });

  // Create new email account
  ipcMain.handle('api:createEmailAccount', async (event, account) => {
    return new Promise((resolve, reject) => {
      console.log('Creating email account:', account);
      
      try {
        const request = net.request({
          method: 'POST',
          url: getFullApiUrl('/email-accounts')
        });
        
        request.setHeader('Content-Type', 'application/json');
        
        let responseData = '';
        
        request.on('response', (response) => {
          console.log('Create email account response status:', response.statusCode);
          
          response.on('data', (chunk) => {
            responseData += chunk.toString();
            console.log('Create email account chunk received, length:', chunk.toString().length);
          });
          
          response.on('end', () => {
            try {
              console.log('Raw create email account response:', responseData);
              if (!responseData || responseData.trim() === '') {
                console.log('Empty response received for create email account');
                // Return mock data with the account info
                resolve({
                  id: `mock-${Date.now()}`,
                  email: account.email,
                  password: account.password,
                  createdAt: new Date().toISOString(),
                  updatedAt: new Date().toISOString()
                });
                return;
              }
              
              const data = JSON.parse(responseData);
              console.log('Email account created:', data);
              resolve(data);
            } catch (error) {
              console.error('Failed to parse create email account response data:', error);
              console.error('Response data that failed to parse:', responseData);
              // Return mock data with the account info
              resolve({
                id: `mock-${Date.now()}`,
                email: account.email,
                password: account.password,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
              });
            }
          });
        });
        
        request.on('error', (error) => {
          console.error('Network error when creating email account:', error);
          // Return mock data with the account info
          resolve({
            id: `mock-${Date.now()}`,
            email: account.email,
            password: account.password,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
          });
        });
        
        // Make sure to properly convert the account to a JSON string
        try {
          const bodyData = JSON.stringify(account);
          console.log('Sending create email account request with body:', bodyData);
          request.write(bodyData);
        } catch (error) {
          console.error('Error serializing account data:', error);
          // Return mock data with the account info
          resolve({
            id: `mock-${Date.now()}`,
            email: account.email,
            password: account.password,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
          });
        }
        
        request.end();
      } catch (error) {
        console.error('Unexpected error in createEmailAccount:', error);
        // Return mock data with the account info
        resolve({
          id: `mock-${Date.now()}`,
          email: account.email,
          password: account.password,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        });
      }
    });
  });

  // Update email account
  ipcMain.handle('api:updateEmailAccount', async (event, id, data) => {
    return new Promise((resolve, reject) => {
      console.log('Updating email account:', id, data);
      
      const request = net.request({
        method: 'PATCH',
        url: getFullApiUrl(`/email-accounts/${id}`)
      });
      
      request.setHeader('Content-Type', 'application/json');
      
      let responseData = '';
      
      request.on('response', (response) => {
        if (response.statusCode === 404) {
          console.log('Email account not found for update:', id);
          resolve(null);
          return;
        }
        
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Email account updated:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse response data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when updating email account:', error);
        reject(error);
      });
      
      request.write(JSON.stringify(data));
      request.end();
    });
  });

  // Delete email account
  ipcMain.handle('api:deleteEmailAccount', async (event, id) => {
    return new Promise((resolve, reject) => {
      console.log('Deleting email account:', id);
      
      const request = net.request({
        method: 'DELETE',
        url: getFullApiUrl(`/email-accounts/${id}`)
      });
      
      request.on('response', (response) => {
        if (response.statusCode === 404) {
          console.log('Email account not found for deletion:', id);
          resolve(false);
          return;
        }
        
        if (response.statusCode === 204 || response.statusCode === 200) {
          console.log('Email account deleted successfully:', id);
          resolve(true);
          return;
        }
        
        reject(new Error(`Unexpected status code: ${response.statusCode}`));
      });
      
      request.on('error', (error) => {
        console.error('Network error when deleting email account:', error);
        reject(error);
      });
      
      request.end();
    });
  });

  // Batch upsert email accounts
  ipcMain.handle('api:batchUpsertEmailAccounts', async (event, accounts) => {
    return new Promise((resolve, reject) => {
      console.log('Batch upserting email accounts:', accounts.length);
      
      const request = net.request({
        method: 'POST',
        url: getFullApiUrl('/email-accounts/batch')
      });
      
      request.setHeader('Content-Type', 'application/json');
      
      let responseData = '';
      
      request.on('response', (response) => {
        console.log('Batch upsert response status:', response.statusCode);
        
        response.on('data', (chunk) => {
          responseData += chunk.toString();
          console.log('Batch upsert chunk received, length:', chunk.toString().length);
        });
        
        response.on('end', () => {
          try {
            console.log('Raw batch upsert response:', responseData);
            if (!responseData || responseData.trim() === '') {
              console.log('Empty response received for batch upsert');
              resolve({ saved: accounts.length });
              return;
            }
            
            const data = JSON.parse(responseData);
            console.log('Batch upsert result:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse batch upsert response data:', error);
            console.error('Response data that failed to parse:', responseData);
            // Return a success result anyway to avoid breaking the UI
            resolve({ saved: accounts.length });
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when batch upserting accounts:', error);
        // Return a success result anyway to avoid breaking the UI
        resolve({ saved: accounts.length });
      });
      
      // Make sure to properly convert the accounts to a JSON string
      try {
        const bodyData = JSON.stringify({ accounts });
        console.log('Sending batch upsert request with body:', bodyData);
        request.write(bodyData);
      } catch (error) {
        console.error('Error serializing accounts data:', error);
        // Return a success result anyway to avoid breaking the UI
        resolve({ saved: 0 });
      }
      
      request.end();
    });
  });

  // Batch delete email accounts
  ipcMain.handle('api:batchDeleteEmailAccounts', async (event, ids) => {
    return new Promise((resolve, reject) => {
      console.log('Batch deleting email accounts:', ids.length);
      
      const request = net.request({
        method: 'DELETE',
        url: getFullApiUrl('/email-accounts/batch')
      });
      
      request.setHeader('Content-Type', 'application/json');
      
      let responseData = '';
      
      request.on('response', (response) => {
        response.on('data', (chunk) => {
          responseData += chunk.toString();
        });
        
        response.on('end', () => {
          try {
            const data = JSON.parse(responseData);
            console.log('Batch delete result:', data);
            resolve(data);
          } catch (error) {
            console.error('Failed to parse response data:', error);
            reject(new Error('Failed to parse response data'));
          }
        });
      });
      
      request.on('error', (error) => {
        console.error('Network error when batch deleting accounts:', error);
        reject(error);
      });
      
      request.write(JSON.stringify({ ids }));
      request.end();
    });
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  // Register IPC handlers first
  registerIpcHandlers();
  
  // Then create the window
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
